#!/bin/bash

SILVER_SCRIPT_LOCATION="$HOME/bin/silver"


#Check if the silver script exists to find the installed location of Silver
if [ ! -f $SILVER_SCRIPT_LOCATION ]; then
    echo "Couldn't find Silver file (~/bin/silver) to find Silver's home"
    exit 1
fi

#These next lines stolen from the Silver script
# ~/bin/silver should be a link to somewhere, find out where!
SILVER_EXECUTABLE=$(readlink -f $SILVER_SCRIPT_LOCATION)
#Set Silver's home
SILVER_HOME=${SILVER_EXECUTABLE/support\/bin\/silver/}
#Set the generated directory where language encodings can be found
SILVER_GENERATED=${SILVER_HOME}generated/extensibella/



#Find the Extensibella home
EXTENSIBELLA_ROOT=$(dirname $(realpath $0))
EXTENSIBELLA_GENERATED=${EXTENSIBELLA_ROOT}/generated/
EXTENSIBELLA_EXAMPLES=${EXTENSIBELLA_ROOT}/exampleEncoding/
export EXTENSIBELLA_LIBRARY=${EXTENSIBELLA_ROOT}/stdLib/



#Add generated dirs and example dir to the directories to search
EXTENSIBELLA_ENCODED=$EXTENSIBELLA_ENCODED:$EXTENSIBELLA_GENERATED
EXTENSIBELLA_ENCODED=$EXTENSIBELLA_ENCODED:$SILVER_GENERATED
EXTENSIBELLA_ENCODED=$EXTENSIBELLA_ENCODED:$EXTENSIBELLA_EXAMPLES
export EXTENSIBELLA_ENCODED



#Location where the jar should be
EXTENSIBELLA_JAR="$EXTENSIBELLA_ROOT/extensibella.jar"
#Check if the jar exists to run
if [ ! -f "$EXTENSIBELLA_JAR" ]; then
    echo "Couldn't find Extensibella jar to execute, aborting."
    exit 2
fi
#Run the interface
java -Xmx4G -Xss16M -jar "$EXTENSIBELLA_JAR" $@

