#!/bin/bash

set -e

sterling --extensibella -I .. compositionTest:host
sterling --extensibella -I .. compositionTest:otherSyntax
sterling --extensibella -I .. compositionTest:typing
sterling --extensibella -I .. compositionTest:moreSyntax
sterling --extensibellaFull -I .. compositionTest:composed

extensibella --check --compile host.xthm
extensibella --check --compile typing.xthm
extensibella --check --compile otherSyntax.xthm
extensibella --check --compile moreSyntax.xthm
extensibella --check composed.xthm

extensibella --compose out.thm compositionTest:composed composed.xthm host.xthm moreSyntax.xthm otherSyntax.xthm typing.xthm ../../../sterling/stdLib/stdLib.xthm

abella out.thm
